name: 'Report Arduino Sketch Size Deltas'
description: 'Comments on the pull request with a report on the resulting change in memory usage of Arduino sketches'
inputs:
  sketches-reports-source:
    description: 'When run from scheduled workflow, name of the workflow artifact that contains sketches reports. When run from a pull request triggered workflow, path to the folder containing sketches reports.'
    default: 'sketches-reports'
  github-token:
    description: 'GitHub access token used to comment the memory usage comparison results to the PR thread'
    default: ${{ github.token }}
  destination-file:
    description: 'Path to file where to save the results, used for PUSH or SCHEDULE events'
    default: ''
  pr-number:
    description: 'Number of PR where to comment the results'
    default: ''
  baseline-branch:
    description: 'Name of the branch the PR is compared against. Used in the report heading. Default: master'
    default: 'master'
  update-comment:
     description: "true: update the previous report with the same heading (create if none). false: always post a new comment."
     default: false
runs:
  using: 'docker'
  image: 'Dockerfile'
